# -*- coding: utf-8 -*-
"""APP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zrYR65x7ZUv-VmlPxKaQBI1Wycy8r9QS
"""

# Import libraries

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Page Configuration
st.set_page_config(
    page_title="Employee Retention Prediction",
    page_icon="📊",
    layout="wide"
)

# App Title
st.title("📊 Employee Retention Prediction System")
st.markdown("### Logistic Regression Based Machine Learning Project")
st.write("---")

# Sidebar
st.sidebar.header("Upload Dataset")

uploaded_file = st.sidebar.file_uploader(
    "Choose a CSV file",
    type=["csv"]
)

# Load Dataset
if uploaded_file is not None:
    df = pd.read_csv(uploaded_file)
    st.success("Dataset uploaded successfully!")
else:
    df = pd.read_csv("HR_comma_sep.csv")
    st.info("Using default dataset (HR_comma_sep.csv)")

# ==========================
# Dataset Preview
# ==========================

st.subheader("📋 Dataset Preview")

st.dataframe(df.head())

# ==========================
# Dataset Information
# ==========================

st.subheader("📊 Dataset Information")

col1, col2 = st.columns(2)

with col1:
    st.write("**Number of Rows:**", df.shape[0])
    st.write("**Number of Columns:**", df.shape[1])

with col2:
    st.write("**Column Names:**")
    st.write(list(df.columns))

# ==========================
# Missing Values
# ==========================
st.header("Missing Values")

missing_values = df.isnull().sum()

# Check total missing values
if missing_values.sum() == 0:
    st.success("No missing values found in the dataset.")
else:
    st.warning("Missing values detected in the dataset.")

    # Show only columns having missing values
    missing_df = missing_values[missing_values > 0].to_frame(name="Missing Values")

    st.dataframe(
        missing_df,
        use_container_width=True
    )

# Salary vs Retention
with col1:

    # Convert numeric salary back to labels only for plotting
    salary_labels = df["salary"].replace({
        0: "Low",
        1: "Medium",
        2: "High"
    })

    salary_chart = pd.crosstab(salary_labels, df["left"])

    fig1, ax1 = plt.subplots(figsize=(4.5,3))

    salary_chart.plot(
        kind="bar",
        ax=ax1,
        width=0.7
    )

    ax1.set_title("Salary vs Employee Retention", fontsize=11)
    ax1.set_xlabel("Salary Level")
    ax1.set_ylabel("Employees")
    ax1.legend(["Stayed", "Left"], fontsize=8)
    ax1.tick_params(axis="x", rotation=0)
    fig1.tight_layout()

    st.pyplot(fig1, use_container_width=False)

# ------------------------------------------
# Department vs Employee Retention
# ------------------------------------------

with col2:

    department_chart = pd.crosstab(df["Department"], df["left"])

    fig2, ax2 = plt.subplots(figsize=(4.5, 2.8))

    department_chart.plot(
        kind="bar",
        ax=ax2,
        width=0.5
    )

    ax2.set_title("Department vs Retention", fontsize=9)
    ax2.set_xlabel("")
    ax2.set_ylabel("Employees", fontsize=8)
    ax2.tick_params(axis='x', labelsize=7, rotation=40)
    ax2.tick_params(axis='y', labelsize=8)
    ax2.legend(
        ["Stayed", "Left"],
        fontsize=7,
        loc="upper right"
    )

    plt.tight_layout()

    st.pyplot(fig2, use_container_width=False)

# ==========================
# Machine Learning Model
# ==========================

st.header(" Logistic Regression Model")

# Convert salary into numerical values
salary_mapping = {
    "low": 0,
    "medium": 1,
    "high": 2
}

df["salary"] = df["salary"].map(salary_mapping)

# Select Features
X = df[[
    "satisfaction_level",
    "average_montly_hours",
    "promotion_last_5years",
    "salary",
    "time_spend_company"
]]

# Target Variable
y = df["left"]

# Split Dataset
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=10
)

# Train Button
if st.button(" Train Model"):

    model = LogisticRegression(max_iter=1000)

    model.fit(X_train, y_train)

    prediction = model.predict(X_test)

    accuracy = accuracy_score(y_test, prediction)

    st.success("Model Trained Successfully!")

    st.metric("Model Accuracy", f"{accuracy*100:.2f}%")

    # Save model in session
    st.session_state["model"] = model

# ==========================
# Employee Retention Prediction
# ==========================

st.header(" Predict Employee Retention")

# Check if model is trained
if "model" in st.session_state:

    satisfaction = st.slider(
        "Satisfaction Level",
        min_value=0.0,
        max_value=1.0,
        value=0.50,
        step=0.01
    )

    monthly_hours = st.number_input(
        "Average Monthly Hours",
        min_value=50,
        max_value=350,
        value=200
    )

    promotion = st.selectbox(
        "Promotion in Last 5 Years",
        ["No", "Yes"]
    )

    salary = st.selectbox(
        "Salary",
        ["Low", "Medium", "High"]
    )

    years = st.number_input(
        "Time Spent in Company (Years)",
        min_value=1,
        max_value=10,
        value=3
    )

col1, col2, col3 = st.columns(3)

col1.metric("👥 Total Employees", len(df))
col2.metric("✅ Stayed", (df["left"] == 0).sum())
col3.metric("❌ Left", (df["left"] == 1).sum())

retention_rate = ((df["left"] == 0).sum() / len(df)) * 100
attrition_rate = ((df["left"] == 1).sum() / len(df)) * 100

col4, col5, col6 = st.columns(3)

col4.metric("📈 Retention Rate", f"{retention_rate:.2f}%")
col5.metric("📉 Attrition Rate", f"{attrition_rate:.2f}%")
col6.metric("🤖 Model Accuracy", f"{accuracy*100:.2f}%")

    # Convert inputs
    promotion = 1
if promotion == "Yes" else 0

    salary_dict = {
        "Low": 0,
        "Medium": 1,
        "High": 2
    }

    salary = salary_dict[salary]

    # Prediction
   if st.button("Predict"):

    # Convert inputs
    promotion = 1 if promotion == "Yes" else 0

    salary = {
        "Low": 0,
        "Medium": 1,
        "High": 2
    }[salary]

    prediction = model.predict([[
        satisfaction,
        monthly_hours,
        promotion,
        salary,
        years
    ]])

    if prediction[0] == 0:
        st.success("Employee is likely to Stay.")
    else:
        st.error("Employee is likely to Leave.")

else:
    st.warning("⚠️Please train the model first by clicking 'Train Model'.")
